config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  resources :learns
  # get 'welcome/index'
  # root 'welcome#index'
  
  get 'start/index'
  root 'start#index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :set_learn, only: [:show, :edit, :update, :destroy]

  # GET /learns
  # GET /learns.json
  def index
    @learns = Learn.all
  end

  # GET /learns/1
  # GET /learns/1.json
  def show
  end

  # GET /learns/new
  def new
    @learn = Learn.new
  end

  # GET /learns/1/edit
  def edit
  end

  # POST /learns
  # POST /learns.json
  def create
    @learn = Learn.new(learn_params)

    respond_to do |format|
      if @learn.save
        format.html { redirect_to @learn, notice: 'Learn was successfully created.' }
        format.json { render :show, status: :created, location: @learn }
      else
        format.html { render :new }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learns/1
  # PATCH/PUT /learns/1.json
  def update
    respond_to do |format|
      if @learn.update(learn_params)
        format.html { redirect_to @learn, notice: 'Learn was successfully updated.' }
        format.json { render :show, status: :ok, location: @learn }
      else
        format.html { render :edit }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learns/1
  # DELETE /learns/1.json
  def destroy
    @learn.destroy
    respond_to do |format|
      format.html { redirect_to learns_url, notice: 'Learn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn
      @learn = Learn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def learn_params
      params.require(:learn).permit(:wow)
    end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
    @msg = 'Welcome to ggHUB'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to ggHUB!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%# The html tag need this class %>
<html class="h-100">
  <head>
    <title>Gghub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%# The body tag needs those classes %>
  <body class="d-flex flex-column h-100 pt-5">
    <header>
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">ggHUB</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Tournamets</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Teams</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Players</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Profile</a>
            </li>
          </ul>
          <a class="nav-link" href="#">Login</a>
          <a class="nav-link" href="/signup">Register</a>
        </div>
      </nav>
    </header>

    <main role="main" class="shrink-flex-0 mb-5">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </main>

    <footer class="footer mt-auto py-3 navbar-dark bg-dark">
      <div class="container">
        <span class="text-muted">Sticky footer test</span>
      </div>
    </footer>
  </body>
</html>

app/views/learns/_form.html.erb
<%= form_with(model: learn, local: true) do |form| %>
  <% if learn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(learn.errors.count, "error") %> prohibited this learn from being saved:</h2>

      <ul>
      <% learn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wow %>
    <%= form.text_field :wow %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/learns/edit.html.erb
<h1>Editing Learn</h1>

<%= render 'form', learn: @learn %>

<%= link_to 'Show', @learn %> |
<%= link_to 'Back', learns_path %>

app/views/learns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Learns</h1>

<table>
  <thead>
    <tr>
      <th>Wow</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @learns.each do |learn| %>
      <tr>
        <td><%= learn.wow %></td>
        <td><%= link_to 'Show', learn %></td>
        <td><%= link_to 'Edit', edit_learn_path(learn) %></td>
        <td><%= link_to 'Destroy', learn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Learn', new_learn_path %>

app/views/learns/new.html.erb
<h1>New Learn</h1>

<%= render 'form', learn: @learn %>

<%= link_to 'Back', learns_path %>

app/views/learns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wow:</strong>
  <%= @learn.wow %>
</p>

<%= link_to 'Edit', edit_learn_path(@learn) %> |
<%= link_to 'Back', learns_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/start/index.html.erb
<div class="container-fluid" style="margin-top: 50px;">
  <div class="row justify-content-around">
    <div class="col-2">
      <h5>New Players</h5>
    </div>
    <div class="col-6">
      <h3>News</h3>
    </div>
    <div class="col-2">
      <h5>New Tournaments</h5>
    </div>
  </div>
  <div class="row justify-content-around">
    <div class="col-2">
      <p class=" mt-2">Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad </p>
    </div>
    <div class="col-6">
      <div class="jumbotron">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </p>
      </div>  
      <div class="jumbotron">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </p>
      </div>
    </div>
    <div class="col-2">
      <p class=" mt-2">Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad Lorem saIUDghasijudasjuhdi sadjgsdaslk  jhasjkdhajkhs asjhdjsahdasl sad </p>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid" style="margin-top: 50px;">
  <% provide(:title, 'Sign up') %>
  <h1>Sign up</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid" style="margin-top: 50px;">
  <% provide(:title, @user.name) %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  </div>
</div>

app/views/welcome/index.html.erb
<%# You need to put your nav inside a header tag %>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

<%# 
This here is just so for show, you don't need it.
If you wanna try what happens with long content, then just
copy paste the h1 tag  
%>

<main role="main" class="shrink-flex-0">
  <div class="container">
    <h1 class="mt-5">Sticky footer</h1>
  </div>
</main>

<%# This is all you need for the footer %>
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Sticky footer test</span>
  </div>
</footer>